### ISSUE TITLE
A related tool

### ISSUE THREAD

**Issue by nnmrts** [krystalgamer/stem-player-emulator#12]
Hey @krystalgamer, thanks for your work, I already used the emulator and it worked perfectly.

This might seem like self promotion but I just wanted to tell you about a "follow-up" tool I made: https://github.com/nnmrts/merge-stems

I also wrote you on reddit about this. I also tried to make a post on reddit about it but the subreddit doesn't allow me to post for some reason. Would be nice if you could tell people about it in your readme or your reddit post or somewhere else, I just want the /r/Kanye community to know about it before they all have to merge their stems themselves.

Cheers!

**Comment by krystalgamer** [comment]
I've checked your post on reddit and it's on moderator approval mode. As you might guess ye related subreddits have been flooded with people asking and begging for download links. Just wait a little someone will approve it.


I deliberately avoided anything related to merging stems because that would mean I'd have to give some kind of support. What I've been suggesting to people that ask me is either use audacity or use sox, both tools are simple enough that it's pretty hard to mess up.

I've taken a look at your tool and it seems to be a `ffmpeg` wrapper and the file size is quite large for such a small use-case, for reference sox is only 2Mb on windows. I don't think it's up to me to market the tool, you could easily do that by forwarding people to it when you see someone asking how to merge the stems.

**Comment by krystalgamer** [comment]
I'll delete this since the user in question has been quite rude in DMs and is mad at me for his post getting blocked on a subreddit which I have no power in.
