### ISSUE TITLE
easy download feature request

### ISSUE THREAD

**Issue by oliviaiacovou** [krystalgamer/stem-player-emulator#21]
![image](https://user-images.githubusercontent.com/20854744/157612856-c2987746-3b47-4b91-b266-469a3212732b.png)
when playing a song from the email section (without the emulator installed, by the way) a link is generated in the network section when inspecting element. if you open the link in a new tab and save the page you can save the entire song in an mp3 with all the stems. hopefully this would be a simple feature to add to make every song download from a single button press

**Comment by krystalgamer** [comment]
i know this and it's a planned feature: https://github.com/krystalgamer/stem-player-emulator/issues/20

With the album stems it was easy to download because the track was downloaded in advance, I could grab the buffer and download it.

Here as you soon you press play there's a bunch of requests being fired to fill the metadata for the tracks and then the track you've chosen is played via MediaSession. As you can see it does by ranged downloads which is great to save bandwidth but is annoying if you want the full track. 

The feature is planned I've been just thinking the best way to implement it that is update resistant.

**Comment by krystalgamer** [comment]
feature added, update the emulator to use the "Download on play" feature :)
