### ISSUE TITLE
TRACK FAILED TO LOAD 

### ISSUE THREAD

**Issue by gandolino** [krystalgamer/stem-player-emulator#33]
The code didn’t work

**Comment by aJtheweirdo78** [comment]
I've had the same problem for a couple of weeks now. I've already given up. Hope you find a solution. 👍

**Comment by krystalgamer** [comment]
if you have the same problem for a couple weeks then I need to ask you for that time traveler gear, since they updated this less than 4 days ago.

also, it's on the readme.

Kano has been updating their website so the emulator might stop working at any time without warning. If you just want to listen to the album then I suggest you to find mirrors online, if you wish to support the emulator then you can donate [here](https://www.paypal.com/donate/?hosted_button_id=N6QZL2267QYLU). 

Money will be used to buy the stemplayer and teardown for further reverse-engineering purposes.
