### ISSUE TITLE
It really doesnt make sense anymore that its not working because of updating when its been months and the same issue is still happening

### ISSUE THREAD

**Issue by bigshnzzz** [krystalgamer/stem-player-emulator#34]
.

**Comment by krystalgamer** [comment]
it is partially working. the device challenge hasn't been implemented because I haven't gotten enough donations to buy an actual stemplayer and disassemble it.

if you wish to contribute then you can do it [here](https://www.paypal.com/donate/?hosted_button_id=N6QZL2267QYLU).

if don't wish to do so then the only thing I can recommend is to get DONDA 2 from one of the multiple available mirrors.
